
<div class="container">
    <div class="page-header">
		<h1 id="">Timeline</h1>
	</div>
	<div id="timeline"><div class="row timeline-movement timeline-movement-top">
    <div class="timeline-badge timeline-future-movement">
        <a href="#">
            <span class="glyphicon glyphicon-plus"></span>
        </a>
    </div>
    <div class="timeline-badge timeline-filter-movement">
        <a href="#">
            <span class="glyphicon glyphicon-time"></span>
        </a>
    </div>

</div>
<div class="row timeline-movement">

    <div class="timeline-badge">
        <span class="timeline-balloon-date-day">18</span>
        <span class="timeline-balloon-date-month">APR</span>
    </div>

<!--due -->
<?php 
foreach($agendas as $key => $value){

  $date = strtotime($value->dt_ocorencia);
  $date = date('H',$date);

  ?>
<div class="row timeline-movement">
    <div class="timeline-badge">
        <span class="timeline-balloon-date-day">13</span>
        <span class="timeline-balloon-date-month">APR</span>
    </div>

    <div class="col-sm-offset-6 col-sm-6  timeline-item">
        <div class="row">
            <div class="col-sm-offset-1 col-sm-11">

            <?php if($date <= 12){
                 echo "<div class='timeline-panel debits'>";

            }else{

                  echo "<div class='timeline-panel credits'>";

            } ?>

                    <ul class="timeline-panel-ul">
                        <li><span class="importo"><?php echo $value->descricao;?></span></li>
                        <li><span class="causale">Lorem ipsum dolor sit amet, consectetur adipiscing elit. </span> </li>
                        <li><p><small class="text-muted"><i class="glyphicon glyphicon-time"></i><?php echo $value->dt_ocorencia;?></small></p> </li>
                    </ul>
                </div>

            </div>
        </div>
    </div>
<?php } ?>
</div>
</div>
</div>