<div class="container">
<?php $flag = isset($flag)?$flag:null;?>

<?php if(isset($retorno)):?>
<div class="alert alert-<?php echo $retorno?>">
<?php echo $retorno; ?>
</div>
<?php endif; ?>
    	<div class="row">
			<div class="col-md-6 col-md-offset-3">
				<div class="panel panel-login">
					<div class="panel-heading">
						<div class="row">
							<div class="col-xs-6">
								<a href="#" class="active" id="login-form-link">Login</a>
							</div>
							<div class="col-xs-6">
									<a href="#" id="register-form-link">Registro</a>
							</div>
							
						</div>
						<hr>
					</div>
					<div class="panel-body">
						<div class="row">
							<div class="col-lg-12">
								<form id="login-form" action="" method="post" role="form" style="<?php echo $flag == 'registro'?'display:none;':'display:block';?>">


								<?php
								/**
								*@see:Constroi o display da msg de retorno a tentativa de acesso
								*@reference: http//bootsnipp.com/snippets/featuder/a-different-approach-to-bootstrap-alert
								*/
								if(isset($msg) && !empty($msg)) : ?>
								<div class="error-notice">
								<div class="error<?php echo $class;?>">
								<strong>error</strong> - <?php echo $msg; ?>
								</div>
								</div>
								
							<?php endif; ?>

									<div class="form-group">
										<input type="text" name="username" id="username" tabindex="1" class="form-control" placeholder="Usuario" value="">
									</div>
									<div class="form-group">
										<input type="password" name="password" id="password" tabindex="2" class="form-control" placeholder="Senha">
									</div>
									
									<div class="form-group">
										<div class="row">
											<div class="col-sm-6 col-sm-offset-3">
												<input type="submit" name="login-submit" id="login-submit" tabindex="4" class="form-control btn btn-login" value="Enviar">
											</div>
										</div>
									</div>
									<div class="form-group">
										<div class="row">
											<div class="col-lg-12">
												<div class="text-center">
													<a href="http://phpoll.com/recover" tabindex="5" class="forgot-password">Esqueceu a sua senha?</a>
												</div>
											</div>
										</div>
									</div>
								</form>
									<form id="register-form" action="<?php echo $this->url('registro'); ?>" method="post" role="form" style="<?php echo $flag == 'registro'?'display:block;':'display:none';?>">
								<?php
								/**
								*@see:Constroi o display da msg de retorno a tentativa de acesso
								*@reference: http//bootsnipp.com/snippets/featuder/a-different-approach-to-bootstrap-alert
								*/
								if(isset($msg) && !empty($msg)) : ?>
								<div class="error-notice">
								<div class="error<?php echo $class;?>">
								<strong>error</strong> - <?php echo $msg; ?>
								</div>
								</div>
								
							<?php endif; ?>
									<div class="form-group">
										<input type="text" name="username" id="username" tabindex="1" class="form-control" placeholder="Usuario" value="">
									</div>
									<div class="form-group">
										<input type="email" name="email" id="email" tabindex="1" class="form-control" placeholder="Email" value="">
									</div>
									<div class="form-group">
										<input type="password" name="password" id="password" tabindex="2" class="form-control" placeholder="Senha">
									</div>
									<div class="form-group">
										<input type="password" name="confirm-password" id="confirm-password" tabindex="2" class="form-control" placeholder="Confirma Senha">
									</div>
									<div class="form-group">
										<div class="row">
											<div class="col-sm-6 col-sm-offset-3">
												<input type="submit" name="registrar" id="registrar" tabindex="4" class="form-control btn btn-register" value="Registrar">
											</div>
										</div>
									</div>
								</form>
							
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>